[package]
name = "tokio-jobs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.72"
chrono = "0.4.26"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"
sysinfo = "0.29.7"
tokio = { version = "1.30.0", features = ["full"] }
